/**
 * MODULE 7 — APPLICATION (formal apply event)
 * module_key: "pipeline_tracker"
 *
 * ADR-1 (candidate pipeline redesign): this module used to own both the
 * "candidate applied via a job posting" event AND all stage/status
 * tracking. Those were two different concerns wearing one table, which
 * meant status could drift between what an application said and what a
 * separately-tracked pipeline said. Stage/status tracking has moved to
 * candidate_tracker (see 18-candidate-tracker.ts) — application is now
 * pure metadata: the fact that a candidate applied to a specific job
 * posting, nothing more. It delegates all status to its linked tracker.
 *
 * Tables:
 *   application — a candidate's formal apply event against a job posting
 *   document    — files attached to a candidate's tracked journey
 *
 * Key design decisions:
 *   - application has no status column. Read status via trackerId →
 *     candidate_tracker.status. One place owns the fact, by construction.
 *   - application requires both jobPostingId and trackerId: it only
 *     exists for the "applied via a posting" entry path. HR adding a
 *     candidate directly (no posting) creates a candidate_tracker row
 *     with no application row at all — application is optional metadata
 *     on top of a tracker, not the other way around.
 *   - document attaches to trackerId, not applicationId: a candidate
 *     added directly by HR has a tracker but may have no application, and
 *     still needs to attach a resume/offer letter/contract.
 */

import {
  pgTable,
  uuid,
  text,
  timestamp,
  pgEnum,
  index,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { pkUuid, orgId, createdAt } from "./_helpers";
import { organisation, user } from "./02-identity";
import { candidate } from "./04-candidates";
import { jobPosting } from "./05-job-postings";
import { candidateTracker } from "./18-candidate-tracker";

// ─── Enums ───────────────────────────────────

export const documentTypeEnum = pgEnum("document_type", [
  "resume",
  "offer_letter",
  "signed_offer",
  "assessment",
  "id_proof",
  "contract",
  "nda",
  "other",
]);

// ─── Tables ──────────────────────────────────

/**
 * application
 * The fact that a candidate applied to a specific job posting. Created
 * together with its candidate_tracker row, in the same transaction, by
 * the applications feature's create flow.
 *
 * entry_source mirrors candidate.source — preserved here because the
 * application may be created differently from how the candidate record
 * was created.
 */
export const application = pgTable("application", {
  id:                   pkUuid(),
  organisationId:       orgId().references(() => organisation.id, { onDelete: "cascade" }),
  candidateId:          uuid("candidate_id").notNull().references(() => candidate.id),
  jobPostingId:         uuid("job_posting_id").notNull().references(() => jobPosting.id, { onDelete: "cascade" }),
  trackerId:            uuid("tracker_id").notNull()
                          .references(() => candidateTracker.id, { onDelete: "cascade" }),

  // How this application was created
  entrySource:          text("entry_source").notNull().default("job_post"),
  // "job_post" | "manual" | "resume_upload" | "referral"

  appliedAt:            timestamp("applied_at", { withTimezone: true })
                          .notNull().default(sql`now()`),
}, (t) => [
  index("app_org_idx").on(t.organisationId),
  index("app_candidate_idx").on(t.candidateId),
  index("app_job_idx").on(t.jobPostingId),
  index("app_tracker_idx").on(t.trackerId),
  // ADR-2's "check application duplicacy later on the job portal" note:
  // this is the cheap, DB-level floor under that — catches a double-submit
  // regardless of what richer UX the portal builds later.
  uniqueIndex("app_candidate_job_unique_idx").on(t.candidateId, t.jobPostingId),
]);

/**
 * document
 * Files attached to a candidate's tracked journey (CVs, offer letters,
 * contracts, etc.) File bytes are stored in object storage (S3/R2/GCS).
 * This table stores metadata + access URL only.
 */
export const document = pgTable("document", {
  id:             pkUuid(),
  organisationId: orgId().references(() => organisation.id, { onDelete: "cascade" }),
  trackerId:      uuid("tracker_id").notNull()
                    .references(() => candidateTracker.id, { onDelete: "cascade" }),
  uploadedBy:     uuid("uploaded_by").notNull().references(() => user.id),

  documentType:   documentTypeEnum("document_type").notNull(),
  fileName:       text("file_name").notNull(),
  fileUrl:        text("file_url").notNull(),
  fileSizeBytes:  text("file_size_bytes"),
  mimeType:       text("mime_type"),

  // Offer letters generated by the platform
  isGenerated:    text("is_generated").default("false"),

  ...createdAt,
}, (t) => [
  index("doc_tracker_idx").on(t.trackerId),
  index("doc_org_idx").on(t.organisationId),
]);
