ALTER TABLE "application" ALTER COLUMN "id" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "application_stage_log" ALTER COLUMN "id" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "audit_log" ALTER COLUMN "id" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "candidate" ALTER COLUMN "id" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "candidate_team_access" ALTER COLUMN "id" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "client" ALTER COLUMN "id" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "client_team_access" ALTER COLUMN "id" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "credit_account" ALTER COLUMN "id" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "credit_cost" ALTER COLUMN "id" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "credit_transaction" ALTER COLUMN "id" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "document" ALTER COLUMN "id" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "event_log" ALTER COLUMN "id" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "goal" ALTER COLUMN "id" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "invitation" ALTER COLUMN "id" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "job_posting" ALTER COLUMN "id" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "job_seeker" ALTER COLUMN "id" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "kpi_definition" ALTER COLUMN "id" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "kpi_entry" ALTER COLUMN "id" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "org_module_override" ALTER COLUMN "id" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "organisation" ALTER COLUMN "id" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "performance_review" ALTER COLUMN "id" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "plan" ALTER COLUMN "id" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "portal_application" ALTER COLUMN "id" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "role" ALTER COLUMN "id" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "stage_action" ALTER COLUMN "id" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "subscription" ALTER COLUMN "id" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "team" ALTER COLUMN "id" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "team_strategy" ALTER COLUMN "id" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "user" ALTER COLUMN "id" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "user_team_role" ALTER COLUMN "id" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "workflow_stage" ALTER COLUMN "id" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "workflow_template" ALTER COLUMN "id" DROP DEFAULT;